services:
  nextjs-app:
    build: . # Aktifkan kembali agar Jenkins bisa build dari Dockerfile
    image: aridutomo12/porto-aridutomo:latest # Opsional: dipakai sebagai nama image hasil build
    container_name: porto-aridutomo
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - web-network # GANTI menjadi web-network agar bisa terhubung ke Nginx & Jenkins

networks:
  web-network:
    external: true
